version: "3.3"

services:
  back:
    image: back
    container_name: back
    build:
      context: ./back
    ports:
      - "9080:9080"
  front:
    image: front
    container_name: front
    build:
      context: ./front
    ports:
      - "8080:80"
    depends_on:
      - back
